arch:

language: python  # Specify the language environment

services:
  - docker  # Use Docker service

before_install:
  - docker build -t imageBuild .  # Build a Docker image from your Dockerfile

script:
  - docker run my-ubuntu-image /bin/sh -c "echo 'Running tests'"  # Replace with your actual test command

branches:
  only:
    - main  # Build only the main branch