services:
  - docker

before_script:
  - echo 'Preparing for build...'

script:
  - START_BUILD_TIME=$(date +%s)  # Start time for the build
  - docker build -t marktest .
  - END_BUILD_TIME=$(date +%s)    # End time for the build
  - echo "Build Time: $(($END_BUILD_TIME - $START_BUILD_TIME)) seconds"
  
  - START_RUN_TIME=$(date +%s)    # Start time for running the container
  - docker run marktest /bin/sh -c 'echo "Hello from inside the container!"'
  - END_RUN_TIME=$(date +%s)      # End time for running the container
  - echo "Run Time: $(($END_RUN_TIME - $START_RUN_TIME)) seconds"

after_success:
  - echo 'Build succeeded!'

after_failure:
  - echo 'Build failed!'

before_cache:
  - docker save -o $HOME/docker_cache.tar marktest

cache:
  directories:
    - $HOME/docker_cache.tar

before_install:
  - docker load -i $HOME/docker_cache.tar || true
